services:
  server:
    container_name: Server
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .docker.env
    depends_on:
      - database
      - ollama
      - redis

  database:
    container_name: Database
    image: postgres:alpine
    restart: always
    shm_size: 128mb
    env_file:
      - .docker.env
    volumes:
      - postgres_data:/var/lib/postgresql

  ollama:
    container_name: Ollama
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    command: serve

  cloudflared:
    container_name: Cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate --url http://server:3000
    depends_on:
      - server

  redis:
    container_name: Redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data:
    name: "Postgres"
  ollama_data:
    name: "Ollama"
  redis_data:
    name: "Redis"
